ipfs/interop

test/exchange-files.js, test/pubsub.js
This commit should be reverted if no fix is found within a time limit, say one week.
Thoughts on the matter:
https://martinfowler.com/articles/nonDeterminism.html
https://blog.arkency.com/weekly-quarantine/
=> fix: temporarily quarantine pubsub tests

test/repo.js
When the `js-ipfs-repo` adds the `datastore_spec` file, as well as the `datastore` property to the config, the repo's will be interoperable again 🚀 
Tested with both PR's needed:
=> fix: repo interop

test/pin.js
On my laptop these tests are slow. On Jenkins workers they are \*really\* slow, so increase the timeout.
```console
pin
pin add
✓ pin recursively (18531ms)
✓ pin directly (16056ms)
pin rm
✓ pin recursively, remove the root pin (12891ms)
✓ remove a child shared by multiple pins (10232ms)
ls
✓ print same pins (9001ms)
go and js pinset storage are compatible
- go -> js
- js -> go
5 passing (1m)
2 pending
```
=> test: increase pin test timeouts

test/utils/daemon.js
Similar to ipfs/js-ipfs-http-client#942 - in my testing using the `test` profile for go and turning off mdns/webrtcstar decreases the time it takes to run the files tests (at least) from 15-45s to 7s
=> test: turn off discovery to make tests run faster

test/circuit/browser.js, test/ipns.js
This reenables the `browser-browser-go` circuit test which is working.
fixes https://github.com/ipfs/interop/issues/16
=> fix: enable browser-browser-go circuit test

.travis.yml, package.json, test/cid-version-agnostic.js, test/pubsub.js, test/utils/daemon.js
Looking into `pull-mplex` updates in js-ipfs I noticed the pubsub tests here needed improvement. For example, JS -> JS and go -> go just use the same node for publishing and subscribing. I refactored the tests to spin up unique nodes for each suite.
This exposed a current issue with go -> js pubsub failing.  I am looking into this.
=> fix: pubsub tests

test/exchange-files.js
The tests are failing against the latest go-ipfs rc candidate (0.4.21-rc.3), https://github.com/ipfs/go-ipfs/issues/6389. This is due to an issue with go announcing its address over MDNS with port 4001 even though the port is actually different. Since the MDNS discovery occurs before dial in the test and fails, the connect attempt will subsequently fail due to JS doing a blacklisting backoff on failed connection attempts. 
While this doesn't solve the underlying issue, we shouldn't have MDNS turned on for these tests. My recommendation is:
> I'd recommend we disable MDNS in the tests for now and file an issue for fixing MDNS so this isn't blocking the release as it's not really a critical issue. In reality we should just move to the new MDNS spec for both implementations and not waste …
=> test: disable mdns in exchange files

package.json, test/files.js, test/node.js
This PR addresses [ipfs/interop#71](https://github.com/ipfs/interop/issues/71). IPNS Pubsub tests were failing on master for linux, as a result of `cids` being outdated on `ipfsd-ctl`
=> chore: update dependencies

test/files.js
Makes sure we have the same hashes for rabin chunking
=> test: add tests for rabin chunking

test/ipns-pubsub.js
We introduced a dial queue on js-libp2p-switch, which intends to (among other factors) blacklist abusive peers. In this test, and differently, to the interop tests for pubsub, we had the default bootstrap list, as well as MDNS discovery enabled. This way, we were discovering the peer in several ways and trying to dial to it, while also dialing explicitly to it, in order to guarantee that each peer knows each other before the IPNS over pubsub tests. 
With this into account, the libp2p-switch was marking the peer as blacklisted and we were not being able to dial with it.
I created this PR, which basically has an empty bootstrap list for the js node, and disables MDNS. This way, we will have the CI green in here and test the interop over the wire. Moreover, I will create an issue in …
=> fix: interop dial blacklist

package-lock.json, package.json, test/circuit/browser.js, test/pubsub.js
js-IPFS v0.38.0 shipped with pubsub enabled by default so it's no longer necessary to pass the enable-pubsub flag to the daemon.
=> fix: fix up pubsub tests

.travis.yml
Disable building branches that aren't master - builds will happen for all PRs anyway, so this change means we don't get a branch build *and* a PR build on each PR.
=> chore: avoid double travis build for PRs

bin/ipfs-interop.js
Lets us keep env config in `package.json` instead of `.travis.yml` and do things like:
```console
$ npm run test:interop:browser
```
which will then invoke a npm script like:
```json
{
"scripts": {
"test:interop:browser": "IPFS_JS_MODULE=`pwd` npm run test:interop -- -t browser"
}
}
```
=> feat: pass extra cli args to npm test command

test/utils/circuit.js
We loop through available multiaddrs looking for certain types of address in our tests.  If there are non of the type we are looking for, we don't return anything which results in undescriptive error messages from libp2p.
The change here is to throw an error with an explicit message if, for example, no webrtc-star address is available when we expect there to be.
=> fix: throw if no requested address is available

.travis.yml, package.json
This will let us run our tests without needing extra installs in .travis.yml.
=> chore: install ipfs, go-ipfs-dep and ipfs-http-client as dev deps

test/ipns.js, test/repo.js
We've changed how we name keys in the keystore but the js-ipfs migration isn't quite ready. The real issue here is that the repo versions differ.
=> fix: all repo compatibility tests

.aegir.js, test/utils/daemon-factory.js
Uses webpack config to override where `require('ipfs')` is resolved to instead of using the `IPFS_JS_MODULE` env var which seems to have stopped working since we stopped including all of the users' env in production builds in aegir.
=> fix: override ipfs module location

.aegir.js, test/files.js, test/pin.js
- fix remote node ipfs http client path
- fix rabin params go-ipfs has validation and returns errors
- fix use cid instead of hash in the pin tests
=> fix: go-ipfs 0.5 sync

package-lock.json, package.json
Should probably have been part of #113?
Also uses the latest js-ipfs.
=> chore: update deps to test against go-ipfs 0.5.x

.aegir.js, README.md, package-lock.json, package.json, test/utils/daemon-factory.js
The `go-ipfs` module does exactly what `go-ipfs-dep` does except it's got a much better name.
The plan is to encourage people to use `go-ipfs` instead as there's no need for us to maintain both.
=> chore: swap go-ipfs-dep for go-ipfs

test/cid-version-agnostic.js, test/exchange-files.js, test/files.js, test/kad-dht.js, test/pin.js, test/repo.js, test/utils/circuit.js
Refactors code to use ipfs.add for single item adds and ipfs.addAll
for multiple items.
=> refactor: ipfs.add only works on single items

package-lock.json, test/ipns-pubsub.js
The `ipns-pubsub` tests were taking 2+ minutes to complete. There was a 60 second delay in the before test. I assume this was added previously due to some timing issues, but this isn't necessary. Additionally, I'm not sure why the ipns resolve statements were being done serially, this just adds to the test time (1 test regularly takes about 60s to complete, likely due to the republish interval but I'm not certain). 
This update removes the unnecessary delay in the `before` and lets the pubsub and regular resolve happen in parallel which **reduces the time by ~2mins**.
| **Before** | **After** |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/639834/88805511-87707e80-d1af-11ea-81d9-c4cb4c2be496.png) | …
=> test: reduce ipns pubsub test duration

test/exchange-files.js, test/files.js, test/pin.js
We need to use ipfs.add for single bits of content and ipfs.addAll for multiple bits of content.
=> fix: use ipfs.addAll for directories

.github/workflows/test.yml, README.md, package.json, scripts/custom-runtime.sh
This PR extracts the glue code from #387  that simplifies running interop against unreleased code of go-ipfs and js-ipfs packages from lerna monorepo.
Goal here is to make it easier to land changes by demonstrating green CI and/or speed up local dev.
See  it in action in #387 where it takes care of running against specific git revisions of go-ipfs, js-ipfs(-http-server) and js-ipfs-http-client :robot: 
(next) I am going to use this for unblocking libp2p as well.
=> feat: scripts/custom-runtime.sh

test/circuit/v1/browser.js, test/utils/circuit.js, test/utils/relayd.js
There aren't enough peers to use the DHT during circuit tests, so disable it for JS the same way it's disabled for Go.
=> fix: disable js dht during circuit tests

.github/workflows/test.yml
Rationale: 
- we finished landing and releasing all the breaking changes around go-ipfs 0.10 and 0.11, and switched to stable release versions of js-ipfs and go-ipfs 
- running on master  here will make it easie for us to determine if interop failures in js-ipfs/go-ipfs CI is upstream issue, or local.
Closes #409
=> chore: restore ci tests on default branch

package-lock.json, package.json
This is a follow up to https://github.com/ipfs/aegir/pull/944.
I bumped the version and ran `npm install`.
=> chore(deps): bump aegir from 36.1.3 to 36.2.3

README.md
@achingbrain lmk if this looks right to you. @lidel and I went through this yesterday as a proposed way to do the interop dance versioning dance.
This is dependent on some of the changes from #387 being extracted and landing in master so that it's really easy to change which commit of go/js-ipfs we're building against in CI.
=> docs: add breaking change interop release process

package.json
We add execa to the browser ignores but we need to add fs and go-ipfs as well.
We can revert this once we drop CJS support since we're changing the package.json generated by ipjs and with just ESM we won't need ipjs any more.
=> fix: add fs and go-ipfs to browser ignores

package-lock.json, package.json, scripts/setup-libp2p-relay-daemon.js, test/utils/circuit.js
This fixes interop tests when Swarm.EnableHolePunching in go-ipfs is
enabled by default.
Ref. https://github.com/ipfs/go-ipfs/pull/8748
=> fix: when hole punching is enabled by default

README.md
There are identical Contribute sections before and after the License section of the README. This PR removes the former with its ToC entry.
=> docs: remove duplicate contribute

test/circuit/v1/all.js
`go-libp2p` v0.26.0 removed (https://github.com/libp2p/go-libp2p/releases/tag/v0.26.00) support for Relay V10. Therefore, Kubo will no longer support it.
Removing. See https://github.com/ipfs/kubo/pull/9656.
=> fix: remove relay v1 go tests
